export const constants = {
    POST_MESSAGE: "POST_MESSAGE",
    POST_MESSAGE_SUCCESS: "POST_MESSAGE_SUCCESS",
    POST_MESSAGE_ERROR: "POST_MESSAGE_ERROR",
    UPDATE_MESSAGES: "UPDATE_MESSAGES",
    SUBSCRIBE_GET_MESSAGES_TO_FIREBASE: "SUBSCRIBE_GET_MESSAGES_TO_FIREBASE",
    UNSUBSCRIBE_GET_MESSAGES_FROM_FIREBASE: "UNSUBSCRIBE_GET_MESSAGES_FROM_FIREBASE"
};